- name: Pull Docker image from Docker Hub
  docker_image:
    name: badido18/database:latest
    source: pull
    state: present

- name: Create Docker container
  docker_container:
    name: database
    image: badido18/database:latest
    state: started
    recreate: yes
    networks:
      - name: simple-net
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    