version: '3.7'

services:
  backend:
    build: ./simple-api-student
    networks:
      - simple-net
    depends_on:
      database:
        # run conditionned by database being fully loaded 
        condition: service_healthy

  database:
    build: ./database
    networks:
      - simple-net
    #  specifying env variables
    environment:
      - POSTGRES_DB = db
      - POSTGRES_USER = usr
      - POSTGRES_PASSWORD = pwd
    volumes:
      - postgres-volume:/var/lib/postgresql/data 
    # check that the database is mounted and all data is loaded
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  httpd:
    build: ./http-server
    # specify the exposed port
    ports:
      - 80:80
    networks:
      - simple-net
    depends_on:
      - backend

  front:
    build: ./devops-front
    networks:
      - simple-net
    depends_on:
      - backend

# Create a volume
volumes:
  postgres-volume:

# specify the network
networks:
  simple-net:
