- name: Pull Docker image from Docker Hub
  docker_image:
    name: badido18/front:latest
    source: pull
    state: present

- name: Create Docker container
  docker_container:
    name: front
    image: badido18/front:latest
    state: started
    networks:
      - name: simple-net
    